language: generic

sudo: false

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libstdc++-4.9-dev

matrix:
  include:
     # Linux
     - os: linux
       compiler: clang
       env: NODE_VERSION="0.10" # node abi 11
     - os: linux
       compiler: clang
       env: NODE_VERSION="4" # node abi 46
     - os: linux
       compiler: clang
       env: NODE_VERSION="6" # node abi 48
     # OS X
     - os: osx
       compiler: clang
       env: NODE_VERSION="0.10" # node abi 11
       osx_image: xcode8.2
     - os: osx
       compiler: clang
       env: NODE_VERSION="4" # node abi 46
       osx_image: xcode8.2
     - os: osx
       compiler: clang
       env: NODE_VERSION="6" # node abi 48
       osx_image: xcode8.2

env:
  global:
    - secure: "HzN2Zl1ADiRXmKs7MHhVnk1DK/BzEPxfzkWVmcKfA4smLyOpZSPx1+2peQju6NU1iekiTd+gOiLdrMfhKfbzD+QU4ee5tlTFupeseWOKG/l8ixc9EMiCvAB41Nqy9B9LEotITRqQOg9GvmkpNzC4EevTq5jUTi++q8chwy9jUyIpgN15G0Gvx/agMxVoA5GXmKoUNASPT9XEadfzh606P7Uh6Evtm58vC4xDvIys9cEJtXDBjy0iwOcnI0F6S3F+Uzi2kuo1d4SU9AHb4ZDbpKC/kRWo+xC23Oaw3WInQwANAi7QJLzx5ZE7IK636hexVG/MU1CzNxmM3jAzC9VMfjSVvIov2ObMGNMfXnoKm3VRvQs020WD5ZNciB9fIp1/XqE9b3qBDKFCWsHXb49gIgsPHYTRxPZXsV5u+EQguXKRI8upb6TWJVGyjM7i5q3olyQ+0BAFLmHJfN8ViibiNjy4IhOc6SpMFpPb4TbAHQlXFfkXBMlBQG5Mptv6jIqO0YYuQ84Hz2aZ+lN4tJRtMAeEdYmqKGRRPuVPgZgpT99p0AO5GCCTi3BT1ZSbZ9JvGPy+qJF10MqO0pQ73ruEB3lhSXKUAYlaelFCOQvkjuUCDCQ38Zrx5CevcZxXptencOZiAeoVNlDF7rL951RkDW8Zef+dehFL7IohN9vr3K4="
    - secure: "mCGuAoX0V75Kl7EBDw5JRZc1KrBglrNdMgFKE7auIl1BFgolHJ0wFodw0F4AZ2uy3SQi3Dfz+yVotpz6NgbLSlqSS1yO66tu0zk0gI3BkaDJ/8A2rfZUNKVEo1nzhM271/9PD0zqS1rUZn5hQPHRwRy7fBNfcXE/CPAvwL8AyBncGB5Iswn2GNett6ffGR+Y7NWBNLePXxiDTBIxVBqBFvvuUschMyuZLdSzKXGMKtKdqVaOihZ3j8tHE7szmnl/wYAO7bT1jhnGnS/K3CcHrZUx+xkppow7UpFD8EcCDgZgs73T1UmVywMaVBvTNznCBlj+qGpsOVbyfo6Xe2DjstBFvJWloTYMoSKwtYNth5rftVnrhKNXdVq+oDuHHtRo/7DnFAfjZErU0QyXBUCBS5MdIoHJrND6U0qODJABBFk86f/4mMEULYzJIYxsp7wP2RpApkGJarvIsaOnAz333ddTeDgamTV6sPka2HbMFgaHQ6lLvc3I4fNdTTMW34xoKVH1D3VKQtAHCeW+L/MUQI6+jFA4Y8XMoh/+IEBXrhh9UayBqjKBYVli/mxmJ7mlq3eMRQMV5hH+kq5KWL3+EzWOXtlyVO7Se5BEqoPuBO5nKKdEtIht3jW9Iy3xnGCVcEEGgg3pOQ41+2yX0vVth8lZ+M/gn04oxTi+1n0heLc="

before_install:
 # install clang++ via mason
 - mkdir /tmp/mason && curl -sSfL https://github.com/mapbox/mason/archive/v0.5.0.tar.gz | tar --gunzip --extract --strip-components=1 --directory=/tmp/mason
 - /tmp/mason/mason install clang++ 3.9.1
 - export PATH=$(/tmp/mason/mason prefix clang++ 3.9.1)/bin:${PATH}
 - export CXX=clang++-3.9
 - source ~/.nvm/nvm.sh
 - nvm install $NODE_VERSION
 - nvm use $NODE_VERSION

install:
 - npm install --build-from-source --clang=1;

script:
 - npm test
 - ./test/travis-publish.sh
